CREATE TABLE IF NOT EXISTS ACCOUNT (
  USERNAME TEXT PRIMARY KEY,
  PASSWORD TEXT NOT NULL,
  REGISTER_DATE DATE NOT NULL,
  USER_TYPE TEXT CHECK(USER_TYPE IN ('resident', 'helper')) NOT NULL
);

INSERT INTO ACCOUNT (USERNAME, PASSWORD, REGISTER_DATE, USER_TYPE) VALUES
('admin', '$2a$10$o39vYF344.UO00cwkC.nJONR4Dg4YPx76i2/84fqmDv76djTzlnei', '2024-01-01', 'resident'),
('jane_smith', '$2a$10$JvFXC5W0BIsjK8yfiqCB5uagpKuQuUnhSIs1ZSKpoC/k4BvmyMhtG', '2024-01-05', 'helper'),
('alex_jones', '$2a$10$JvFXC5W0BIsjK8yfiqCB5uagpKuQuUnhSIs1ZSKpoC/k4BvmyMhtG', '2024-01-10', 'resident'),
('john_doe', '$2a$10$JvFXC5W0BIsjK8yfiqCB5uagpKuQuUnhSIs1ZSKpoC/k4BvmyMhtG', '2024-01-11', 'resident');

CREATE TABLE IF NOT EXISTS PROPOSAL (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE TEXT,
  PROP_DESC TEXT NOT NULL,
  REGISTER_DATE DATE NOT NULL,
  FAVOR INTEGER DEFAULT 0,
  AGAINST INTEGER DEFAULT 0,
  TOTAL_VOTES INTEGER DEFAULT 0
);

INSERT INTO PROPOSAL (TITLE, PROP_DESC, REGISTER_DATE, FAVOR, AGAINST) VALUES
('Proposal 1', 'Description of proposal 1', '2024-01-01', 10, 2),
('Proposal 2', 'Description of proposal 2', '2024-01-15', 5, 3),
('Proposal 3', 'Description of proposal 3', '2024-02-01', 8, 1);

CREATE TABLE IF NOT EXISTS VOTE (
  USERNAME TEXT NOT NULL,
  PROPOSAL_ID INTEGER NOT NULL,
  VOTE_TYPE TEXT CHECK(VOTE_TYPE IN ('favor', 'against')) NOT NULL,
  VOTE_DATE DATE NOT NULL,
  PRIMARY KEY (USERNAME, PROPOSAL_ID),
  FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME),
  FOREIGN KEY (PROPOSAL_ID) REFERENCES PROPOSAL(ID)
);

INSERT INTO VOTE (USERNAME, PROPOSAL_ID, VOTE_TYPE, VOTE_DATE) VALUES
('john_doe', 1, 'favor', '2024-01-02'),
('john_doe', 2, 'against', '2024-01-16'),
('jane_smith', 1, 'favor', '2024-01-03'),
('alex_jones', 3, 'favor', '2024-02-02'),
('jane_smith', 2, 'against', '2024-01-17');